/* Readable C reconstruction of the 68000-side PLAYER.S control/runtime core.
 *
 * This file intentionally preserves Jaguar-era integer widths and state ordering.
 * Weapon, collectable, pain and movement/collision paths are represented here
 * or in their corresponding translated modules; the exact preservation tree
 * remains the binary oracle.
 */
#include "player.h"
#include "jaguar_hw.h"
#include "joypad.h"
#include "maze.h"
#include "mazescrn.h"
#include "doors.h"
#include "levels.h"
#include "amp.h"
#include "avp_runtime.h"
#include "collectables.h"
#include "weapons.h"
#include "hud.h"
#include "collision.h"
#include <stdint.h>
#include <stddef.h>

#define MNRG_MAX 1000
#define ANRG_MAX 1125
#define PNRG_MAX 3000
#define RESCALE 85
#define ACC_SHIFT 4
#define DEC_SHIFT 2
#define MAZE_BLOCK_SHIFT 3

volatile u16 seed0,seed1;
s32 x_vel,y_vel;
s16 ang_vel,ang_acc,max_avel,acc_shift,dec_shift;
u32 max_speed;
u16 player_vel;
s16 player_type,player_energy,max_energy,old_energy,pain;
s16 player_dead,game_over,key_lock,destruct_flag,launch_flag;
s32 score;
u32 pain_cols,new_pos,old_pos;
s16 cheat;
u8 wep_fire,one_fire,plreset_count;
u16 fade_c,xtra_c,invisflag;
u8 invis_act,invis_stat,medpak_act;
u16 predo,predo_count;
static u32 predo_ID;
u32 bg_fx;
s16 bg_repeat,bg_delay,bg_count,last_bg;

/* Owned by other translated modules / runtime glue. */
extern u32 savegame;
extern s16 show_mt;
extern u8 acs_level;
extern s16 hugkill,use_cocoon;
extern s16 new_wepno;
extern u32 x_pos,y_pos;
extern u16 maze_width;
extern u32 centre_angle;
extern void readpad(void),InitAccess(void),ResetAccess(void),InitDoors(void),ResetDoors(void);
extern void InitHUD(void),ResetHUD(void),ResetClct(void),DoorKeys(void),Collectables(void);


/* Symbolic SFX IDs are intentionally abstract here until AVPSOUND is converted. */
enum { SFX_AMB2=0, SFX_AMB3=1 };

static void controller_noop(void) { }
extern void (*x_read)(void);
void (*init_move)(void)=InitMove;
void (*reset_move)(void)=ResetMove;
extern void MovePlayer(void);
void (*do_move)(void)=MovePlayer;

static const u16 nrg_maxes[3]={MNRG_MAX,ANRG_MAX,PNRG_MAX};
/* Exact 16-entry CRY pain-colour ramps generated by the source `pain` macro. */
static const u16 human_pain[16]={0x8780,0x8784,0x9688,0x968c,0xa590,0xa594,0xb498,0xb49c,0xc3a0,0xc3a4,0xd2a8,0xd2ac,0xe1b0,0xe1b4,0xf0b8,0xf0bc};
static const u16 alien_pain[16]={0x7780,0x7784,0x7688,0x768c,0x6590,0x6594,0x6498,0x649c,0x53a0,0x53a4,0x52a8,0x52ac,0x41b0,0x41b4,0x40b8,0x40bc};
static const u16 pred_pain[16]={0x8980,0x8988,0x9a90,0x9a98,0x9ba0,0x9ba8,0xacb0,0xacb8,0xadc0,0xadc8,0xbed0,0xbed8,0xbfe0,0xbfe8,0xcff0,0xcff8};
static const u16 *const pain_lists[3]={human_pain,alien_pain,pred_pain};

void StdController(void) {
    init_move=InitMove; reset_move=ResetMove; do_move=MovePlayer; x_read=controller_noop;
}

void InitPlayer(void) {
    unsigned pi=(unsigned)player_type >> 2;
    score=0; cheat=0;
    init_move();
    if (pi>2) pi=0;
    max_energy=(s16)nrg_maxes[pi];
    player_energy=max_energy;
    pain_cols=(u32)(uintptr_t)pain_lists[pi];
    player_dead=game_over=key_lock=launch_flag=destruct_flag=0;
    wep_fire=one_fire=plreset_count=0;
    InitAccess();
    init_random();
    fade_c=0x8880u; xtra_c=0x8880u;
    bg_fx=0;
    predo_ID=0; invis_act=0; invis_stat=0; medpak_act=0; predo=0; predo_count=0; invisflag=0;
    InitDoors();
    InitHUD();

    if (savegame) {
        const u8 *p=(const u8 *)(uintptr_t)savegame;
        /* Jaguar is big-endian; explicit loads keep host-side tests honest. */
        #define BE32(q) ((u32)(q)[0]<<24 | (u32)(q)[1]<<16 | (u32)(q)[2]<<8 | (u32)(q)[3])
        u32 packed;
        score=BE32(p+4);
        packed=BE32(p+16);
        player_energy=(s16)(packed>>16);
        acs_level=(u8)((packed>>12)&0x0fu);
        show_mt=(packed & (1u<<11)) ? -1 : 0;
        #undef BE32
    }
}

void ResetPlayer(void) {
    old_energy=player_energy; pain=0;
    reset_move();
    ResetAccess(); ResetDoors();
    new_pos=0;
    ResetHUD(); ResetClct();
}

void init_random(void) { seed0=AVP_MMIO16(0x00F00004u); seed1=AVP_MMIO16(0x00F00006u); }

u16 avp_random(void) {
    u16 a=seed0,b=seed1;
    a=(u16)((a<<3)|(a>>13)); a=(u16)(a-7u); a^=b;
    seed0=b; seed1=a;
    return b; /* original EXG leaves D0=old seed1 */
}

void BGSounds(void) {
    u16 r=avp_random();
    u16 single=(u16)(r&127u);
    if (single<4u) { const AvpRuntimeOps *o=avp_runtime_ops(); if(o->play_sfx) o->play_sfx(o->user,single<2u ? SFX_AMB2 : SFX_AMB3); }

    r=(u16)((r>>8)|(r<<8));
    if ((r&511u)==0u && bg_fx==0u) {
        /* PLAYER.S currently selects the first bg_fxs entry. Keep the table
         * ownership outside this core until AVPSOUND data is translated. */
        /* The table itself is retail AVPSOUND data.  Keep ownership at the
         * resource/backend boundary; this state mirrors the source scheduler. */
        bg_fx=1; bg_repeat=1; bg_delay=30; bg_count=1;
    }
    if (!bg_fx) return;
    if (--bg_count!=0) return;
    if (--bg_repeat<0) { bg_fx=0; return; }
    bg_count=bg_delay;
    /* The historical do_sfx call is commented out in the supplied source. */
}

void UpdatePlayer(void) {
    readpad();
    if (!hugkill && !use_cocoon && !key_lock) DoorKeys();
    do_move();
    TidyMove();

    if (key_lock) {
        wep_fire=0;
        if (player_type==PT_ALIEN) new_wepno=2;
    } else {
        if (player_type!=PT_ALIEN) Collectables();
        PlayerWeapons(); MapKeys(); ChangeLevel(); Pain(); TestKeys(); ExtraKeys();
    }
    MoveDoors(); BGSounds();
}

void ResetMove(void) { ang_vel=0; x_vel=0; y_vel=0; }

void InitMove(void) {
    static const u16 move_speeds[3]={
        (14000u*RESCALE)/100u,(20000u*RESCALE)/100u,(14000u*RESCALE)/100u
    };
    static const u16 move_angs[3][2]={{0x300,0x600},{0x300,0x900},{0x300,0x600}};
    unsigned pi=(unsigned)player_type>>2;
    if (pi>2) pi=0;
    max_speed=move_speeds[pi];
    acc_shift=ACC_SHIFT; dec_shift=DEC_SHIFT;
    if (player_type==PT_ALIEN) --acc_shift;
    ang_acc=(s16)move_angs[pi][0]; max_avel=(s16)move_angs[pi][1];
}



/* Final retail control mapping documented in MAIN/KEYS.TXT.  Jaguar inputs are
 * active-low: a zero bit means pressed. */
static int pressed(u32 v,unsigned bit){ return (v&(1u<<bit))==0u; }

u8 allow_lcs,allow_god;
extern u8 map_on,show_coords;
extern s16 use_cocoon;
static u32 last_moan;

void MovePlayer(void)
{
    u32 keys=joy_cur;
    s16 req_turn=0,av=ang_vel;
    s32 ax=0,ay=0,nx,ny;
    s32 sa=sin_ang,ca=cos_ang;
    int turn_mode=(player_type==PT_ALIEN)?pressed(keys,OPTION):pressed(keys,FIRE_C);
    const AvpRuntimeOps *ops=avp_runtime_ops();

    if(turn_mode){
        if(pressed(keys,JOY_RIGHT)) req_turn=(s16)-ang_acc;
        if(pressed(keys,JOY_LEFT))  req_turn=(s16) ang_acc;
    }
    if(req_turn){
        if(av && ((av^req_turn)<0)) av=0;
        {
            s32 nv=(s32)av+req_turn,lim=max_avel;
            if(nv>lim) nv=lim;
            if(nv<-lim) nv=-lim;
            av=(s16)nv;
        }
    } else av=0; /* retail build uses the immediate-stop branch */
    ang_vel=av;
    {
        u16 a=(u16)((centre_angle>>16)+(u16)av),low=(u16)(a&0x3fffu);
        if(low<(u16)ang_acc) a=(u16)(a&0xc000u);
        centre_angle=(centre_angle&0x0000ffffu)|((u32)a<<16);
    }

    sa >>= acc_shift; ca >>= acc_shift;
    if(!lift_key){ if(pressed(keys,JOY_UP)){ax+=ca;ay-=sa;} if(pressed(keys,JOY_DOWN)){ax-=ca;ay+=sa;} }
    sa >>= 1; ca >>= 1;
    /* Option is the documented sidestep modifier for non-Alien players.  Alien
     * uses Option for turn mode in this source revision; C preserves that split. */
    if(!turn_mode){ if(pressed(keys,JOY_RIGHT)){ax+=sa;ay+=ca;} if(pressed(keys,JOY_LEFT)){ax-=sa;ay-=ca;} }

    {
        s32 vx=x_vel-(x_vel>>dec_shift),vy=y_vel-(y_vel>>dec_shift);
        s32 sx=(vx<0)?-1:0,sy=(vy<0)?-1:0;
        u32 ux=(vx<0)?(u32)(-(s64)vx):(u32)vx,uy=(vy<0)?(u32)(-(s64)vy):(u32)vy;
        u32 approx=ux+uy+2u*(ux>uy?ux:uy);
        vx+=ax; vy+=ay;
        if(!ax&&!ay && approx<(0x200u*3u)) vx=vy=0;
        if(ax||ay){
            u32 ms=max_speed*3u;
            u32 avx=(vx<0)?(u32)(-(s64)vx):(u32)vx,avy=(vy<0)?(u32)(-(s64)vy):(u32)vy;
            u32 ap=avx+avy+2u*(avx>avy?avx:avy);
            if(ap>ms){ vx-=ax; vy-=ay; }
        }
        (void)sx;(void)sy; x_vel=vx;y_vel=vy;
    }

    if((x_vel|y_vel)==0) return;
    nx=(s32)x_pos+x_vel; ny=(s32)y_pos+y_vel;
    /* Use a host override when present, otherwise execute the translated
     * COLLIDE.S routines directly.  Runtime callbacks therefore remain an
     * optional acceleration/debug boundary, not a missing gameplay dependency. */
    #define WALL_SAFE(px,py) (ops->safe_pos ? ops->safe_pos(ops->user,(px),(py),80,40) : (SafePos(80,(px),(py),40)==AVP_COLL_SAFE))
    #define AMP_SAFE(px,py)  (ops->amp_collision ? ops->amp_collision(ops->user,(px),(py)) : !AMPCollisions((px),(py)))
    if(!WALL_SAFE(nx,ny)){
        s32 ox=nx,oy=ny;
        nx=(s32)x_pos; /* try Y only */
        if(WALL_SAFE(nx,oy) && AMP_SAFE(nx,oy)){ x_vel=0; ny=oy; }
        else {
            y_vel=0; nx=ox; ny=(s32)y_pos; /* try X only */
            if(!(WALL_SAFE(nx,ny) && AMP_SAFE(nx,ny))){ nx=(s32)x_pos;ny=(s32)y_pos;x_vel=0; }
        }
    } else if(!AMP_SAFE(nx,ny)) { nx=(s32)x_pos;ny=(s32)y_pos;x_vel=y_vel=0; }
    #undef WALL_SAFE
    #undef AMP_SAFE
    x_pos=(u32)nx;y_pos=(u32)ny;
}

/* PLAYER.S Predovision state machine.  Hardware VMODE writes are represented
 * by xtra_c plus the runtime/backend presentation boundary; gameplay-visible
 * invisflag and flicker timing remain here. */
void do_predo(void)
{
    static const u16 extra[5]={0x9558u,0x0cf8u,0x8880u,0x26f8u,0x8880u};
    const AvpRuntimeOps *o=avp_runtime_ops();
    if(invis_stat==0) return;
    if(invis_act){
        if(invis_stat!=2){
            if(o->play_sfx)o->play_sfx(o->user,60u);
            predo_ID=1; invis_stat=2; invisflag=(u16)(1u<<AMP_INVHIT); predo_count=3;
            predo=(u16)((predo+20u-8u)%20u);
        } else if(predo_count) --predo_count;
        else { predo_count=2; if(o->play_sfx)o->play_sfx(o->user,60u); predo_ID=1; }
    } else {
        if(invis_stat!=1){
            if(predo_ID && o->play_sfx)o->play_sfx(o->user,60u);
            predo_ID=0; invis_stat=1; predo_count=3;
        }
        if(predo_count) --predo_count;
        else { invisflag=0; invis_stat=0; xtra_c=0x8880u; return; }
    }
    predo=(u16)((predo+4u)%20u);
    xtra_c=extra[predo/4u];
}

void PlayerWeapons(void)
{
    u32 e=joy_edge,c=joy_cur;
    wep_fire=one_fire=0;
    if(player_type==PT_PREDATOR){
        if(pressed(e,OPTION)) invis_act=(u8)~invis_act;
        medpak_act=0;
        /* Retail `test_key medpak,d5`: held medpak control.  The reconstructed
         * input map uses KEY_7 for this otherwise platform-defined action. */
        if(pressed(c,KEY_7)) medpak_act=(u8)~medpak_act;
        do_predo();
    }
    if(player_type==PT_ALIEN){
        new_wepno=2;
        if(pressed(c,FIRE_A)){new_wepno=2;wep_fire=0xff;}
        if(pressed(c,FIRE_B)){new_wepno=3;wep_fire=0xff;}
        if(pressed(c,FIRE_C)){new_wepno=1;wep_fire=0xff;}
        return;
    }
    if(pressed(c,FIRE_A)){wep_fire=0xff;if(pressed(e,FIRE_A))one_fire=0xff;}
    { const unsigned bits[4]={KEY_1,KEY_2,KEY_3,KEY_4}; int pick=0; for(int i=0;i<4;i++)if(pressed(e,bits[i]))pick=i+1; if(pick&&(cur_weps&(1u<<pick)))new_wepno=(s16)pick; }
}

void MapKeys(void){ if(pressed(joy_edge,KEY_8)) map_on^=0xffu; }
void ChangeLevel(void)
{
    if(!allow_lcs) return;
    if(pressed(joy_edge,FIRE_A) && pressed(joy_cur,OPTION)){ s16 n=(s16)(cur_level+1);if(n>AVP_MAX_LEVEL)n=1;new_level=n; }
    else if(pressed(joy_edge,FIRE_B) && pressed(joy_cur,OPTION)){ s16 n=(s16)(cur_level-1);if(n<1)n=AVP_MAX_LEVEL;new_level=n; }
}
void ExtraKeys(void)
{
    /* Retail TEST_LEVELS path: Option+5/8 changes access. */
    if(pressed(joy_cur,OPTION)){
        if(pressed(joy_edge,KEY_5)&&acs_level<10)++acs_level;
        if(pressed(joy_edge,KEY_8)&&acs_level>0)--acs_level;
    }
    if(allow_god && pressed(joy_edge,KEY_0) && pressed(joy_cur,OPTION)) cheat=(s16)~cheat;
}
void TestKeys(void){ /* NO_DEBUG retail build compiles the debug test body out. */ }

void Pain(void)
{
    s32 p=pain;
    if(player_energy>0){
        s16 delta=(s16)(old_energy-player_energy);old_energy=player_energy;
        if(delta>0){
            p+=(s32)delta+50;
            if((u32)(frame_counter-last_moan)>10u){
                const AvpRuntimeOps *o=avp_runtime_ops();last_moan=frame_counter;
                if(o->play_sfx)o->play_sfx(o->user,40u+((unsigned)(player_type>>2)*4u)+(avp_random()&3u));
            }
        } else p-=20;
    } else p-=20;
    if(p<=0){pain=0;fade_c=0x8880u;return;}
    if(p>99)p=99;
    pain=(s16)p;
    {
        unsigned idx=(unsigned)(((u32)p*16u)/100u);if(idx>15)idx=15;
        if(!destruct_flag)fade_c=pain_lists[player_type==PT_ALIEN?1:player_type==PT_PREDATOR?2:0][idx];
    }
}


/* PLAYER.S TestSpark/shoot_loop: source-shaped hitscan against active AMPs.
 * The Jaguar wall-distance helper is exposed through AvpRuntimeOps; if a host
 * backend does not provide it, the weapon's authored maximum distance is used. */
AvpAmp *TestSpark(void)
{
    const AvpRuntimeOps *o=avp_runtime_ops();
    AvpAmp *best=NULL;
    s64 best_z=INT64_MAX;
    u16 ang;
    s32 ca,sa;
    u32 maxdist=fire_distance,wall=0;
    if(!wep_fire)return NULL;
    ang=(u16)(centre_angle>>16);
    ca=cos_d0(ang);sa=-sin_d0(ang);
    if(o->fire_distance && o->fire_distance(o->user,(s32)x_pos,(s32)y_pos,ang,&wall) && wall)maxdist=wall;
    for(unsigned i=0;i<AVP_NUM_AMPS;i++){
        AvpAmp *a=&amps_at[i];s64 dx,dy,z,xoff;u32 width;
        if((!a->mode&&!a->host_static)||!(a->flags&(1u<<AMP_KILLABLE)))continue;
        dx=(s64)a->xpos-(s32)x_pos;dy=(s64)a->ypos-(s32)y_pos;
        z=(dx*ca+dy*sa)>>14; if(z<0 || (u64)z>(u64)maxdist)continue;
        xoff=(dx*sa-dy*ca)>>14;if(xoff<0)xoff=-xoff;
        width=(u32)fire_width<<9;if((u64)xoff>(u64)width)continue;
        if(z<best_z){best_z=z;best=a;}
    }
    if(best){best->energy=(s16)(best->energy-fire_damage);best->flags|=(u16)((1u<<AMP_PHIT)|(1u<<AMP_CLOSEHIT)|invisflag);if(player_type==PT_HUMAN)make_spark_at(best->xpos,best->ypos,0);return best;}
    if(player_type==PT_HUMAN && wall){s32 sx=(s32)(((s64)ca*(s64)wall)>>14),sy=(s32)(((s64)sa*(s64)wall)>>14);make_spark_at((s32)x_pos+sx,(s32)y_pos+sy,0);}
    return NULL;
}

void TidyMove(void) {
    u32 ax=(x_vel<0)?(u32)(-(s64)x_vel):(u32)x_vel;
    u32 ay=(y_vel<0)?(u32)(-(s64)y_vel):(u32)y_vel;
    u32 small=ax,large=ay;
    if (large<small) { u32 t=large; large=small; small=t; }
    player_vel=(u16)(large+(small>>2));
    u16 av=(u16)(ang_vel<0 ? -ang_vel : ang_vel);
    av=(u16)(av<<2);
    if (player_vel<=av) player_vel=av;

    old_pos=new_pos;
    /* Source indexes MAZE_DATA by high words of 16.16 world coordinates and
     * uses (maze_width+2) cells per row, each cell 8 bytes.  The public C
     * decomp stores the byte offset instead of a host pointer. */
    u32 gx=x_pos>>16, gy=y_pos>>16;
    new_pos=((gy*(u32)(maze_width+2u))+gx)<<MAZE_BLOCK_SHIFT;
}

